apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: sallma-ray-cluster
spec:
  rayVersion: "2.10.0"
  headGroupSpec:
    serviceType: ClusterIP
    replicas: 1
    template:
      spec:
        containers:
        - name: ray-head
          image: <your-dockerhub>/ray-head:latest
          command: ["ray", "start", "--head"]
  workerGroupSpecs:
    - groupName: ray-worker
      replicas: 2
      template:
        spec:
          containers:
          - name: ray-worker
            image: <your-dockerhub>/ray-worker:latest
            command: ["ray", "start", "--address=ray://sallma-ray-cluster-head"]