FROM python:3.10-slim

WORKDIR /app

# Install core system dependencies
RUN apt-get update && apt-get install -y \
    gcc curl git && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Default CMD
CMD ["bash"]